/**
 * `pnpm deck:import` — the player YAML files, generated from the owner's CSVs.
 *
 * `players.csv` is the master copy of the deck; the YAML in `players/` is
 * output. Two optional side files join on `player_id`: `image-log.csv` supplies
 * the image block and `focus.csv` the crop focus for the few photos that need
 * one. The CSV format is in `players-csv-format.md` at the repo root.
 *
 * This file is the pure half: text in, a plan out, no filesystem. Every row is
 * mapped, then checked with the same zod schema and deck checks the build
 * uses, so a file is only ever planned for a player the build will accept.
 * `import-cli.ts` reads the files, prints the report and writes the plan.
 *
 * See ARCHITECTURE.md §6.
 */

import { isDeepStrictEqual } from "node:util";
import { Document, isCollection, parse } from "yaml";
import { CsvError, parseCsv } from "./csv.js";
import type { CsvRow, CsvTable } from "./csv.js";
import { playerSchema, toPlayer } from "./schema.js";
import type { RawPlayer } from "./schema.js";
import { validateDeck } from "./validate.js";

export const GENERATED_HEADER =
  "# Generated by pnpm deck:import from players.csv. Edit the CSV, not this file.";

const PLAYER_REQUIRED = ["player_id", "name", "country", "position", "dob"] as const;
const COUNT_COLUMNS = ["club_goals", "caps", "apps", "igoals", "ct", "it", "clubs"] as const;
const PLAYER_COLUMNS = [
  ...PLAYER_REQUIRED,
  "deceased",
  "iconic",
  ...COUNT_COLUMNS,
  "ig_millions",
  "ig_as_of",
  "fee_eur_m",
  "fee_year",
  "era",
  "main_clubs",
  "leagues",
  "notes",
] as const;
const STAT_COLUMNS = new Set<string>([
  ...COUNT_COLUMNS,
  "ig_millions",
  "ig_as_of",
  "fee_eur_m",
  "fee_year",
]);

const IMAGE_REQUIRED = ["player_id", "file", "author", "licence", "source"] as const;
const IMAGE_COLUMNS = [...IMAGE_REQUIRED, "width", "height", "notes"] as const;
const FOCUS_COLUMNS = ["player_id", "focus"] as const;

export interface ImportInputs {
  /** `players.csv`. Required. */
  readonly players: string;
  /** `image-log.csv`, if it exists. */
  readonly imageLog?: string;
  /** `focus.csv`, if it exists. */
  readonly focus?: string;
  /** File names present in `originals/`, for the missing-photo warning. */
  readonly originals: readonly string[];
  /** YAML files already in `players/`: file name → contents. */
  readonly existing: ReadonlyMap<string, string>;
  /** Reference date for the deck checks (dates in the future, age). */
  readonly now: Date;
}

export interface SkippedRow {
  readonly row: number;
  readonly playerId: string;
  /** Every problem with the row, each naming its column. */
  readonly problems: readonly string[];
}

export interface ImportPlan {
  readonly ok: true;
  /** Valid players, in `players.csv` order: id → file contents. */
  readonly files: ReadonlyMap<string, string>;
  readonly created: readonly string[];
  readonly changed: readonly string[];
  readonly unchanged: readonly string[];
  readonly skipped: readonly SkippedRow[];
  /** Imported with `fee` left out, because `fee_year` is still blank. */
  readonly feeNeedsYear: readonly string[];
  readonly imageIdsWithoutPlayer: readonly string[];
  readonly focusIdsWithoutImage: readonly string[];
  /** Imported players with no image block. */
  readonly withoutImage: readonly string[];
  /** One line per id that appears more than once in any of the three files. */
  readonly duplicates: readonly string[];
  /** `id: file` for image-log files that are not in `originals/`. */
  readonly missingOriginals: readonly string[];
  /** Files in `players/` that no `players.csv` row generates. Kept unless pruned. */
  readonly unknownFiles: readonly string[];
}

/** A problem that stops the whole import: nothing is written. */
export interface ImportFailure {
  readonly ok: false;
  readonly fatal: readonly string[];
}

// ---------------------------------------------------------------------------
// Reading the tables

function readTable(
  name: string,
  text: string,
  known: readonly string[],
  required: readonly string[],
  fatal: string[],
): CsvTable | undefined {
  let table: CsvTable;
  try {
    table = parseCsv(text);
  } catch (err) {
    if (err instanceof CsvError) {
      fatal.push(`${name}: ${err.message}`);
      return undefined;
    }
    throw err;
  }

  // Strict on column names: a misspelt header would otherwise read as a
  // column of blanks, and every player would quietly lose that stat.
  const missing = required.filter((c) => !table.header.includes(c));
  const unknown = table.header.filter((c) => !known.includes(c));
  if (missing.length > 0) fatal.push(`${name}: missing column(s) ${missing.join(", ")}`);
  if (unknown.length > 0) {
    fatal.push(
      `${name}: unknown column(s) ${unknown.join(", ")} — expected only ${known.join(", ")}`,
    );
  }
  return missing.length > 0 || unknown.length > 0 ? undefined : table;
}

/** Rows grouped by `player_id`, skipping rows with a blank id. */
function byId(table: CsvTable | undefined): Map<string, CsvRow[]> {
  const out = new Map<string, CsvRow[]>();
  for (const row of table?.rows ?? []) {
    const id = row.cells.player_id ?? "";
    if (id === "") continue;
    const list = out.get(id);
    if (list) list.push(row);
    else out.set(id, [row]);
  }
  return out;
}

function rowList(rows: readonly CsvRow[]): string {
  return rows.map((r) => r.row).join(", ");
}

// ---------------------------------------------------------------------------
// Mapping one row

/**
 * A plain number and nothing else: digits, an optional leading minus and an
 * optional decimal part. `1,234`, `€77m` and `506 apps` are refused rather
 * than guessed at. Sign and whole-number rules are left to the schema, which
 * words them properly.
 */
const PLAIN_NUMBER = /^-?\d+(\.\d+)?$/;

class RowProblems {
  readonly byColumn = new Map<string, string[]>();

  add(column: string, message: string): void {
    const list = this.byColumn.get(column);
    if (list) list.push(message);
    else this.byColumn.set(column, [message]);
  }

  has(column: string): boolean {
    return this.byColumn.has(column);
  }

  get size(): number {
    return this.byColumn.size;
  }

  lines(): string[] {
    return [...this.byColumn].flatMap(([column, messages]) =>
      messages.map((m) => `${column}: ${m}`),
    );
  }
}

function number(cells: CsvRow["cells"], column: string, problems: RowProblems): number | undefined {
  const cell = cells[column] ?? "";
  if (cell === "") return undefined;
  if (!PLAIN_NUMBER.test(cell)) {
    problems.add(
      column,
      `"${cell}" is not a plain number — digits only, no commas, units or symbols`,
    );
    return undefined;
  }
  return Number(cell);
}

function flag(cells: CsvRow["cells"], column: string, problems: RowProblems): true | undefined {
  const cell = cells[column] ?? "";
  if (cell === "") return undefined;
  if (cell.toLowerCase() === "yes") return true;
  problems.add(column, `"${cell}" must be yes or blank`);
  return undefined;
}

function list(cells: CsvRow["cells"], column: string, problems: RowProblems): string[] | undefined {
  const cell = cells[column] ?? "";
  if (cell === "") return undefined;
  if (cell.includes(",")) {
    problems.add(column, `"${cell}" — lists are separated by semicolons, not commas`);
    return undefined;
  }
  const names = cell
    .split(";")
    .map((n) => n.trim())
    .filter((n) => n !== "");
  return names.length > 0 ? names : undefined;
}

/** The CSV column a schema or deck-check path came from, so problems name what to fix. */
function columnFor(
  path: string,
  imageRow: number | undefined,
  focusRow: number | undefined,
): string {
  const [head, second, third] = path.split(".");
  if (head === "id") return "player_id";
  if (head === "stats") {
    if (second === "ig") return third === "as_of" ? "ig_as_of" : "ig_millions";
    if (second === "fee") return third === "year" ? "fee_year" : "fee_eur_m";
    return second ?? "stats";
  }
  if (head === "image") {
    if (second === "focus") return `focus.csv row ${focusRow ?? "?"} focus`;
    return `image-log.csv row ${imageRow ?? "?"} ${second ?? "file"}`;
  }
  return head ?? "(row)";
}

interface Mapped {
  readonly problems: RowProblems;
  readonly raw?: RawPlayer;
  readonly feeNeedsYear: boolean;
}

function mapRow(
  row: CsvRow,
  imageRow: CsvRow | undefined,
  focusRow: CsvRow | undefined,
  now: Date,
): Mapped {
  const c = row.cells;
  const problems = new RowProblems();

  if (row.overflow.length > 0) {
    problems.add(
      "(row)",
      `${row.overflow.length} cell(s) past the last column (${row.overflow.map((v) => `"${v}"`).join(", ")}) — ` +
        `probably an unquoted comma shifting the row`,
    );
  }
  for (const column of PLAYER_REQUIRED) {
    if ((c[column] ?? "") === "") problems.add(column, "is required");
  }

  const stats: Record<string, unknown> = {};
  for (const column of COUNT_COLUMNS) {
    const value = number(c, column, problems);
    if (value !== undefined) stats[column] = value;
  }

  const igValue = number(c, "ig_millions", problems);
  const igAsOf = c.ig_as_of ?? "";
  if (igValue !== undefined && igAsOf !== "") stats.ig = { value: igValue, as_of: igAsOf };
  else if (igValue !== undefined) problems.add("ig_as_of", "is required when ig_millions is set");
  else if (igAsOf !== "" && !problems.has("ig_millions")) {
    problems.add("ig_millions", `is blank but ig_as_of is "${igAsOf}"`);
  }

  // A fee without its year is expected while years are still being
  // collected: leave the fee out and say so, rather than skipping the player.
  // A year without a fee is a mistake.
  const feeValue = number(c, "fee_eur_m", problems);
  const feeYear = number(c, "fee_year", problems);
  let feeNeedsYear = false;
  if (feeValue !== undefined && feeYear !== undefined)
    stats.fee = { value: feeValue, year: feeYear };
  else if (feeValue !== undefined && !problems.has("fee_year")) feeNeedsYear = true;
  else if (feeYear !== undefined && !problems.has("fee_eur_m")) {
    problems.add("fee_eur_m", `is blank but fee_year is ${feeYear}`);
  }

  const deceased = flag(c, "deceased", problems);
  const iconic = flag(c, "iconic", problems);
  const mainClubs = list(c, "main_clubs", problems);
  const leagues = list(c, "leagues", problems);

  let image: Record<string, string> | undefined;
  const file = imageRow?.cells.file ?? "";
  if (imageRow !== undefined && file !== "") {
    image = {
      file,
      author: imageRow.cells.author ?? "",
      licence: imageRow.cells.licence ?? "",
      source: imageRow.cells.source ?? "",
    };
    const focus = focusRow?.cells.focus ?? "";
    if (focus !== "") image.focus = focus;
  }

  const candidate = {
    id: c.player_id ?? "",
    name: c.name ?? "",
    country: c.country ?? "",
    position: c.position ?? "",
    dob: c.dob ?? "",
    ...(deceased !== undefined ? { deceased } : {}),
    ...(iconic !== undefined ? { iconic } : {}),
    ...((c.era ?? "") !== "" ? { era: c.era } : {}),
    ...(mainClubs !== undefined ? { main_clubs: mainClubs } : {}),
    ...(leagues !== undefined ? { leagues } : {}),
    stats,
    ...(image !== undefined ? { image } : {}),
  };

  // The schema runs even when the cells already had problems, so the owner
  // sees every problem with the row at once. A column that already failed is
  // not reported twice.
  const parsed = playerSchema.safeParse(candidate);
  if (!parsed.success) {
    for (const issue of parsed.error.issues) {
      const column = columnFor(issue.path.join("."), imageRow?.row, focusRow?.row);
      if (!problems.has(column)) problems.add(column, issue.message);
    }
    return { problems, feeNeedsYear };
  }

  // The deck's own checks, one player at a time. Duplicate ids are caught
  // before this, across the whole file.
  const statCellFailed = [...problems.byColumn.keys()].some((k) => STAT_COLUMNS.has(k));
  for (const p of validateDeck([parsed.data], [toPlayer(parsed.data)], now)) {
    // "Too few stats" is a consequence of a stat that didn't parse, not a
    // separate problem.
    if (p.field === "stats" && statCellFailed) continue;
    problems.add(columnFor(p.field, imageRow?.row, focusRow?.row), p.message);
  }

  return problems.size > 0
    ? { problems, feeNeedsYear }
    : { problems, raw: parsed.data, feeNeedsYear };
}

// ---------------------------------------------------------------------------
// Writing YAML

/** Keys in the order of the ARCHITECTURE.md §5 example, so output is stable and reads the same. */
function ordered(raw: RawPlayer): Record<string, unknown> {
  const s = raw.stats;
  const stats: Record<string, unknown> = {};
  for (const key of COUNT_COLUMNS) if (s[key] !== undefined) stats[key] = s[key];
  if (s.ig !== undefined) stats.ig = { value: s.ig.value, as_of: s.ig.as_of };
  if (s.fee !== undefined) stats.fee = { value: s.fee.value, year: s.fee.year };

  const out: Record<string, unknown> = {
    id: raw.id,
    name: raw.name,
    country: raw.country,
    position: raw.position,
    dob: raw.dob,
  };
  if (raw.deceased !== undefined) out.deceased = raw.deceased;
  if (raw.iconic !== undefined) out.iconic = raw.iconic;
  if (raw.era !== undefined) out.era = raw.era;
  if (raw.main_clubs !== undefined) out.main_clubs = raw.main_clubs;
  if (raw.leagues !== undefined) out.leagues = raw.leagues;
  out.stats = stats;
  if (raw.image !== undefined) {
    const { file, author, licence, source, focus } = raw.image;
    out.image = { file, author, licence, source, ...(focus !== undefined ? { focus } : {}) };
  }
  return out;
}

/**
 * The player as YAML, in the style of the sample deck: lists and the two
 * stat objects on one line, no line folding. `ig` and `fee` hold only numbers
 * and a date, so padding their braces to match is a safe text edit.
 */
export function playerYaml(raw: RawPlayer): string {
  const doc = new Document(ordered(raw));
  for (const path of [["main_clubs"], ["leagues"], ["stats", "ig"], ["stats", "fee"]]) {
    const node = doc.getIn(path, true);
    if (isCollection(node)) node.flow = true;
  }
  const body = doc
    .toString({ lineWidth: 0, flowCollectionPadding: false })
    .replace(/^( {2}(?:ig|fee): )\{(.*)\}$/gm, "$1{ $2 }");
  const text = `${GENERATED_HEADER}\n${body}`;

  // Belt and braces: what was written must read back as exactly this player.
  const reread = playerSchema.safeParse(parse(text));
  if (!reread.success || !isDeepStrictEqual(reread.data, raw)) {
    throw new Error(
      `deck:import: YAML for ${raw.id} does not read back identically — this is a bug`,
    );
  }
  return text;
}

// ---------------------------------------------------------------------------
// The plan

export function planImport(inputs: ImportInputs): ImportPlan | ImportFailure {
  const fatal: string[] = [];
  const players = readTable("players.csv", inputs.players, PLAYER_COLUMNS, PLAYER_REQUIRED, fatal);
  const images =
    inputs.imageLog !== undefined
      ? readTable("image-log.csv", inputs.imageLog, IMAGE_COLUMNS, IMAGE_REQUIRED, fatal)
      : undefined;
  const focus =
    inputs.focus !== undefined
      ? readTable("focus.csv", inputs.focus, FOCUS_COLUMNS, FOCUS_COLUMNS, fatal)
      : undefined;
  if (players === undefined || fatal.length > 0) return { ok: false, fatal };

  const playerRows = byId(players);
  const imageRows = byId(images);
  const focusRows = byId(focus);

  const duplicates: string[] = [];
  for (const [name, rows] of [
    ["players.csv", playerRows],
    ["image-log.csv", imageRows],
    ["focus.csv", focusRows],
  ] as const) {
    for (const [id, list] of rows) {
      if (list.length > 1) duplicates.push(`${name}: ${id} on rows ${rowList(list)}`);
    }
  }

  const files = new Map<string, string>();
  const skipped: SkippedRow[] = [];
  const feeNeedsYear: string[] = [];
  const withoutImage: string[] = [];

  for (const row of players.rows) {
    const id = row.cells.player_id ?? "";
    const imageList = imageRows.get(id) ?? [];
    const focusList = focusRows.get(id) ?? [];

    // Two rows for one id can't be told apart — which image, which figures?
    // Skip the player rather than pick one.
    const clash: string[] = [];
    if ((playerRows.get(id)?.length ?? 0) > 1) {
      clash.push(`player_id: "${id}" is on rows ${rowList(playerRows.get(id)!)} — keep one`);
    }
    if (imageList.length > 1) {
      clash.push(`image-log.csv: "${id}" is on rows ${rowList(imageList)} — keep one`);
    }
    if (focusList.length > 1) {
      clash.push(`focus.csv: "${id}" is on rows ${rowList(focusList)} — keep one`);
    }

    const mapped = mapRow(row, imageList[0], focusList[0], inputs.now);
    const problems = [...clash, ...mapped.problems.lines()];
    if (mapped.raw === undefined || problems.length > 0) {
      skipped.push({ row: row.row, playerId: id === "" ? "(blank)" : id, problems });
      continue;
    }

    files.set(id, playerYaml(mapped.raw));
    if (mapped.feeNeedsYear) feeNeedsYear.push(id);
    if (mapped.raw.image === undefined) withoutImage.push(id);
  }

  // Compared ignoring line endings: a checkout with autocrlf has CRLF files
  // that git considers identical to what we'd write.
  const created: string[] = [];
  const changed: string[] = [];
  const unchanged: string[] = [];
  for (const [id, text] of files) {
    const before = inputs.existing.get(`${id}.yaml`);
    if (before === undefined) created.push(id);
    else if (before.replace(/\r\n/g, "\n") === text) unchanged.push(id);
    else changed.push(id);
  }

  // Anything in players/ that no row accounts for. A skipped row's old file
  // is accounted for — it is kept, not orphaned.
  const unknownFiles = [...inputs.existing.keys()]
    .filter((name) => !(name.endsWith(".yaml") && playerRows.has(name.slice(0, -".yaml".length))))
    .sort();

  const withImage = new Set<string>();
  for (const [id, list] of imageRows)
    if (list.some((r) => (r.cells.file ?? "") !== "")) withImage.add(id);

  const originals = new Set(inputs.originals);
  const missingOriginals: string[] = [];
  for (const [id, list] of imageRows) {
    for (const r of list) {
      const file = r.cells.file ?? "";
      if (file !== "" && !originals.has(file)) missingOriginals.push(`${id}: ${file}`);
    }
  }

  return {
    ok: true,
    files,
    created,
    changed,
    unchanged,
    skipped,
    feeNeedsYear,
    imageIdsWithoutPlayer: [...imageRows.keys()].filter((id) => !playerRows.has(id)),
    focusIdsWithoutImage: [...focusRows.keys()].filter(
      (id) => !withImage.has(id) || !playerRows.has(id),
    ),
    withoutImage,
    duplicates,
    missingOriginals,
    unknownFiles,
  };
}
