/**
 * Test fixtures.
 *
 * Deliberately invented players with round, easy-to-reason-about numbers.
 * Real names are avoided so nothing here can be mistaken for deck data or
 * quietly copied into it — the real deck is hand-sourced and lives in the
 * private submodule.
 */

import type { Player } from "../types.js";

export const NOW = new Date("2026-09-17T00:00:00Z");

export const fixtureDeck: readonly Player[] = [
  {
    id: "alpha",
    name: "Alpha Striker",
    country: "Testland",
    position: "FW",
    dob: "1980-01-01",
    iconic: true,
    stats: {
      club_goals: 400,
      caps: 100,
      apps: 600,
      igoals: 50,
      ct: 20,
      it: 2,
      clubs: 4,
      ig: { value: 80, asOf: "2026-09-01" },
      fee: { value: 60, year: 2005 },
    },
  },
  {
    id: "bravo",
    name: "Bravo Winger",
    country: "Testland",
    position: "FW",
    dob: "1985-06-15",
    iconic: true,
    stats: {
      club_goals: 200,
      caps: 80,
      apps: 500,
      igoals: 25,
      ct: 10,
      it: 1,
      clubs: 5,
      ig: { value: 40, asOf: "2026-09-01" },
      fee: { value: 30, year: 2010 },
    },
  },
  {
    id: "charlie",
    name: "Charlie Midfield",
    country: "Otherland",
    position: "MF",
    dob: "1978-03-20",
    stats: {
      club_goals: 100,
      caps: 120,
      apps: 700,
      igoals: 10,
      ct: 15,
      it: 0,
      clubs: 3,
      ig: { value: 10, asOf: "2026-09-01" },
      fee: { value: 15, year: 2002 },
    },
  },
  {
    id: "delta",
    name: "Delta Defender",
    country: "Otherland",
    position: "DF",
    dob: "1982-11-05",
    stats: {
      club_goals: 20,
      caps: 90,
      apps: 650,
      igoals: 2,
      ct: 12,
      it: 1,
      clubs: 2,
      ig: { value: 5, asOf: "2026-09-01" },
      fee: { value: 20, year: 2006 },
    },
  },
  {
    id: "echo",
    name: "Echo Keeper",
    country: "Thirdland",
    position: "GK",
    dob: "1975-07-07",
    stats: {
      // No club_goals or igoals — goalkeeper.
      caps: 150,
      apps: 800,
      ct: 18,
      it: 3,
      clubs: 2,
      ig: { value: 12, asOf: "2026-09-01" },
      fee: { value: 25, year: 2001 },
    },
  },
  {
    id: "foxtrot",
    name: "Foxtrot Journeyman",
    country: "Fourthland",
    position: "MF",
    dob: "1988-02-28",
    stats: {
      club_goals: 50,
      caps: 10,
      apps: 400,
      igoals: 0, // legitimate zero — capped but never scored
      ct: 0,
      it: 0,
      clubs: 11,
      ig: { value: 1, asOf: "2026-09-01" },
      fee: { value: 5, year: 2012 },
    },
  },
  {
    id: "golf",
    name: "Golf Veteran",
    country: "Fifthland",
    position: "DF",
    dob: "1970-12-12",
    deceased: true, // excluded from the age stat
    stats: {
      club_goals: 30,
      caps: 60,
      apps: 550,
      igoals: 3,
      ct: 8,
      it: 0,
      clubs: 6,
      fee: { value: 8, year: 1998 },
      // No ig — predates the platform.
    },
  },
  {
    id: "hotel",
    name: "Hotel Prodigy",
    country: "Sixthland",
    position: "FW",
    dob: "1992-09-09",
    iconic: true,
    stats: {
      club_goals: 150,
      caps: 45,
      apps: 300,
      igoals: 20,
      ct: 6,
      it: 1,
      clubs: 3,
      ig: { value: 120, asOf: "2026-09-01" },
      fee: { value: 90, year: 2016 },
    },
  },
  {
    id: "india",
    name: "India Anchor",
    country: "Sixthland",
    position: "MF",
    dob: "1983-04-18",
    stats: {
      club_goals: 75,
      caps: 70,
      apps: 620,
      igoals: 8,
      ct: 14,
      it: 2,
      clubs: 4,
      ig: { value: 3, asOf: "2026-09-01" },
      fee: { value: 12, year: 2007 },
    },
  },
  {
    id: "juliet",
    name: "Juliet Fullback",
    country: "Seventhland",
    position: "DF",
    dob: "1986-08-24",
    stats: {
      club_goals: 12,
      caps: 55,
      apps: 480,
      igoals: 1,
      ct: 9,
      it: 0,
      clubs: 7,
      ig: { value: 2, asOf: "2026-09-01" },
      fee: { value: 18, year: 2011 },
    },
  },
  {
    id: "kilo",
    name: "Kilo Poacher",
    country: "Eighthland",
    position: "FW",
    dob: "1979-05-30",
    stats: {
      club_goals: 320,
      caps: 95,
      apps: 560,
      igoals: 40,
      ct: 11,
      it: 1,
      clubs: 8,
      ig: { value: 25, asOf: "2026-09-01" },
      fee: { value: 45, year: 2004 },
    },
  },
  {
    id: "lima",
    name: "Lima Sweeper",
    country: "Ninthland",
    position: "DF",
    dob: "1974-10-02",
    stats: {
      club_goals: 8,
      caps: 110,
      apps: 720,
      igoals: 0, // another legitimate zero
      ct: 22,
      it: 3,
      clubs: 2,
      ig: { value: 4, asOf: "2026-09-01" },
      fee: { value: 22, year: 1999 },
    },
  },
];
