/**
 * `pnpm blocklist:build` — turns the plain nickname blocklist into the hashed
 * data the Worker ships (worker/src/moderation.ts).
 *
 * The plain list is `worker/blocklist.local.txt`, gitignored: the repo is
 * public, so only hashes are committed (`worker/src/blocklist-data.ts`). Keep a
 * copy of the plain list somewhere private; the hashes can't be turned back
 * into it.
 *
 * Format, one term per line: `any <term>` (matched anywhere in a name) or
 * `word <term>` (only as a whole word or the whole name). `#` starts a comment.
 * Spell a term with a double letter only where the double is what makes it
 * the term (see moderation.ts).
 *
 *   pnpm blocklist:build                 # read the list, write the data
 *   pnpm blocklist:build --check <name>  # does a name pass the current list?
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { blockedTerm, createModerator } from "../worker/src/moderation.js";
import type { BlockedTerm, TermTier } from "../worker/src/moderation.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(root, "worker", "blocklist.local.txt");
const TARGET = join(root, "worker", "src", "blocklist-data.ts");

export function parseBlocklist(text: string): { tier: TermTier; term: string }[] {
  const terms: { tier: TermTier; term: string }[] = [];
  text.split(/\r?\n/).forEach((raw, i) => {
    const line = raw.replace(/#.*/, "").trim();
    if (line === "") return;
    const match = /^(any|word)\s+(\S.*)$/.exec(line);
    if (match === null) throw new Error(`line ${i + 1}: expected "any <term>" or "word <term>"`);
    terms.push({ tier: match[1] as TermTier, term: (match[2] ?? "").trim() });
  });
  return terms;
}

export function blocklistModule(terms: readonly BlockedTerm[]): string {
  const seen = new Set<string>();
  const rows = terms
    .filter((t) => {
      const key = `${t.tier}:${t.hash}:${t.runs?.join(",") ?? ""}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .sort((a, b) => a.tier.localeCompare(b.tier) || a.hash.localeCompare(b.hash))
    .map((t) => {
      const runs = t.runs === undefined ? "" : `, runs: [${t.runs.join(", ")}]`;
      return `  { tier: "${t.tier}", hash: "${t.hash}", length: ${t.length}${runs} },`;
    });
  return [
    "/**",
    " * The nickname blocklist, hashed (worker/src/moderation.ts). Generated by",
    " * `pnpm blocklist:build` from worker/blocklist.local.txt, which is gitignored:",
    " * the plain terms are never in the repo. Don't edit by hand.",
    " */",
    "",
    'import type { BlockedTerm } from "./moderation.js";',
    "",
    "// prettier-ignore",
    "export const BLOCKLIST: readonly BlockedTerm[] = [",
    ...rows,
    "];",
    "",
  ].join("\n");
}

function main(args: readonly string[]): number {
  if (!existsSync(SOURCE)) {
    console.error(
      `blocklist: ${relative(root, SOURCE)} not found. It is gitignored; restore it from your private copy.`,
    );
    return 1;
  }
  const terms = parseBlocklist(readFileSync(SOURCE, "utf8")).map((t) =>
    blockedTerm(t.tier, t.term),
  );
  const check = args.indexOf("--check");
  if (check !== -1) {
    const name = args.slice(check + 1).join(" ");
    const passes = createModerator(terms)(name);
    console.log(`${JSON.stringify(name)}: ${passes ? "passes" : "blocked"}`);
    return 0;
  }
  writeFileSync(TARGET, blocklistModule(terms));
  console.log(`blocklist: ${terms.length} term(s) → ${relative(root, TARGET)}`);
  return 0;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
